### ISSUE TITLE
Doesn't affect Windows system processes

### ISSUE THREAD

**Issue by Undisputed00x** [keifufu/cute-borders#10]
This mod works perfectly except on some system processes (tested so far) like TaskManager, TaskScheduler etc. Executing the mod with admin privileges fixes this issue but doesn't persist after a reboot even if enabling the mod's startup in its config file.

<details><summary>Example Picture</summary>
<p>

![339050896-298089d0-eeb7-439b-8311-f22dd66bed96](https://github.com/keifufu/cute-borders/assets/80290008/bce4322d-ac58-4142-a0b2-19ca668d94ed)

</p>
</details> 

An easy way to resolve the issue is to launch at logon by creating a task schedule with admin privileges enabled

**Comment by keifufu** [comment]
I can't actually find a way to launch it as administrator upon logon with task scheduler.
"Run with highest privileges" appears to do nothing when running on logon.

**Comment by Undisputed00x** [comment]
@keifufu yeah, i also noticed that. Its a little weird way but by adding 1 sec delay apparently fixes the problem.
**Edit**: better apply 5 seconds delay

**Comment by keifufu** [comment]
Wow that is a... microsoft moment? I'll take it. Thank you for figuring that out.

**Comment by keifufu** [comment]
See [v1.2.0](https://github.com/keifufu/cute-borders/releases/tag/1.2.0)

**Comment by Undisputed00x** [comment]
@keifufu Installation works!

Uninstall doesn't work lol 😅.It just closes the mod but startup task schedule remains (i don't care tbh mod works nicely now).

**Comment by keifufu** [comment]
It remains, yes. but it sets the trigger to disabled!

**Comment by Undisputed00x** [comment]
> It remains, yes. but it sets the trigger to disabled!

It doesn't in my case.

**Comment by keifufu** [comment]
![image](https://github.com/keifufu/cute-borders/assets/45028317/c0e2ccd5-8fc3-47ea-bea8-568e81d233f5)
Are you sure?

**Comment by keifufu** [comment]
It will automatically install if launched as administrator btw, so if you uninstall and then launch as admin it will be installed again.

**Comment by Undisputed00x** [comment]
@keifufu You're right, i spoke too fast anyways thank you!
