### ISSUE TITLE
Rainbow border

### ISSUE THREAD

**Issue by markox92** [keifufu/cute-borders#11]
Is possible to have rainbow border options, does Windows API allow something like this? I found that Windows terminal already have this options.

**Comment by keifufu** [comment]
If I understand correctly, this cycles through colors, but there is no gradient in the border, right?

**Comment by markox92** [comment]
Yeah cycles through colors, not sure if there is options to define colors or maybe colors is defined by system.

**Comment by keifufu** [comment]
This is possible, but definitely not a priority. I might look into this at some point if I feel like it.

I no longer use windows myself and have only recently installed a vm to maintain some of my windows software to some degree.
