### ISSUE TITLE
Can you add support for accent color automatically?

### ISSUE THREAD

**Issue by Dhyfer1** [keifufu/cute-borders#13]
Hi @keifufu 👋

I discovered your repo today and it looks cool, and from what I see cute-borders doesn't follow the accent color. I haven't tested it, but the repo doesn't say so, maybe because it doesn't have that feature?

If it doesn't have that feature, I would like cute-borders to be able to customize the border color of certain programs with the accent color.

That's all.

**Comment by keifufu** [comment]
I don't see a reason not to add this, however I am not currently working on this project. I might get around to it when I feel like it. Thank you for the suggestion!

**Comment by Dhyfer1** [comment]
Ok. I hope you take the time to add this feature, I'm sure it would be easy for you. 

Well, I will wait for the next version for this.

**Comment by AndreGoressi** [comment]
> I don't see a reason not to add this, however I am not currently working on this project. I might get around to it when I feel like it. Thank you for the suggestion!

//here is an example code how to add it
https://github.com/tauri-apps/tauri/discussions/5305#discussioncomment-3983903

**Comment by keifufu** [comment]
Thanks, will add this soon.

**Comment by AndreGoressi** [comment]
> Thanks, will add this soon.

No Problem :)

**Comment by Dhyfer1** [comment]
Hi dev.

Thanks for the update, it does what I asked for at the beginning, I like it a lot 😊

Btw, would it be possible, as a feature, to have cute-borders work in the file explorer context menu and customize the border width?

**Comment by keifufu** [comment]
I believe not, context menus likely work different than windows so there is not much I can do there.

As for the border width... I would have to draw them myself in my own "invisible" windows that follow the other windows around, which is a pain. I did experiment with it on the direct2d branch (#1) but have decided that was too much work, especially since I no longer use windows myself.

**Comment by Dhyfer1** [comment]
About the context menu, it's fine, I understand, it doesn't matter. 

But I would like to see a wider custom border, two and three pixels wide is what I would like to see. I hope you will take this feature into account

**Comment by keifufu** [comment]
As I've said, I will not implement it due to it being an entirely different process from just 1px borders (which are drawn by windows itself, and I just have to provide the color).

**Comment by Dhyfer1** [comment]
Well, okay, thanks anyway
