### ISSUE TITLE
folder properties problem

### ISSUE THREAD

**Issue by ntrs05** [keifufu/cute-borders#14]
![Screenshot 2024-08-24 203248](https://github.com/user-attachments/assets/757801da-b485-4652-887c-1168826e314d)

I see a problem in folder properties window, is it possible to fix this?

**Comment by keifufu** [comment]
whatever windows "skin" you're using is probably at fault here

**Comment by ntrs05** [comment]
oh, I see. Thanks, I only see this glitch on this window and not others
