### ISSUE TITLE
Can you add .exe Name Support ?

### ISSUE THREAD

**Issue by AndreGoressi** [keifufu/cute-borders#15]

**Comment by keifufu** [comment]
why?

**Comment by AndreGoressi** [comment]
> why?

since you have to enter the exact window name this function is also language-dependent with the .exe function this would not matter because you then need the name of the .exe and not the language-dependent window name

**Comment by keifufu** [comment]
there is a reason the class match exists

**Comment by AndreGoressi** [comment]
> there is a reason the class match exists

can i use that to add: example "app.exe" ?

**Comment by keifufu** [comment]
I know ShareX has a window inspector tool (or similar) that will show you the class names of certain windows.

**Comment by AndreGoressi** [comment]
> I know ShareX has a window inspector tool (or similar) that will show you the class names of certain windows.

when inspect the mediaplayer app then i get this: ApplicationFrameWindow, but has hardly anything to do with the app itself as the .exe has the name Microsoft.Media.Player.exe

**Comment by keifufu** [comment]
The media player at least always has the title "Media Player", of course this would likely change if you were to change languages but you could simple add multiple rules.

I can see a lot of programs don't have unique class names so I get the frustration there.
I could make a match for the process's file name, however in microsofts media players case this would also be "ApplicationFrameHost.exe" for some inexplicable reason.

**Comment by AndreGoressi** [comment]
> The media player at least always has the title "Media Player", of course this would likely change if you were to change languages but you could simple add multiple rules.
> 
> I can see a lot of programs don't have unique class names so I get the frustration there. I could make a match for the process's file name, however in microsofts media players case this would also be "ApplicationFrameHost.exe" for some inexplicable reason.

yes that would be the process name instead of the name of the exe would be much better even :)

**Comment by keifufu** [comment]
Please make use of the existing matches. Implementing this seems to be a bit annoying.
You are of course welcome to open a PR if you implement it yourself.
