### ISSUE TITLE
blurred hax code dont more work

### ISSUE THREAD

**Issue by AndreGoressi** [keifufu/cute-borders#16]
the code for an blurred border like the original in Windows 11 dont more work since the latest update pls fix.
the code is: #00ffffff

**Comment by keifufu** [comment]
I'm not sure what you mean by blurred border

**Comment by AndreGoressi** [comment]
> I'm not sure what you mean by blurred border

the "burred is the default inactive "color" of an Window in Windows 11

**Comment by keifufu** [comment]
Does it set the color to red?

**Comment by AndreGoressi** [comment]
> Does it set the color to red?

yes

**Comment by AndreGoressi** [comment]
here that i mean
<img width="198" alt="Screenshot 2024-09-06 173741" src="https://github.com/user-attachments/assets/c535ad28-57ac-4363-8514-54ff3c9a057b">

**Comment by keifufu** [comment]
Then it only worked previously because invalid colors would default to that, now they default to RED to indicate something is wrong. I will add an option to get the "blurred" borders in a few hours.

**Comment by AndreGoressi** [comment]
but "accent" and "rainbow" works :)

**Comment by AndreGoressi** [comment]
can you add this "burred" to the config as "default" ?

**Comment by keifufu** [comment]
yes

**Comment by AndreGoressi** [comment]
> yes

ok good and here btw for the get_process_name stuff: https://stackoverflow.com/questions/70252985/get-external-process-id-by-name

**Comment by keifufu** [comment]
Sorry this does not help in the slightest. I iterate though windows, not processes. I have their handles and could get their process handles from it but that just seems like a bunch of unnecessary api calls.

**Comment by keifufu** [comment]
Especially since I do not cache anything but just keep polling it =w=

**Comment by AndreGoressi** [comment]
> Especially since I do not cache anything but just keep polling it =w=

ok good now it is much more important anyway that the previously mentioned hax code works again and that it can even be set as “default” in the config

**Comment by keifufu** [comment]
the hex code will not work since it is still invalid, but "default" will work.

**Comment by AndreGoressi** [comment]
> the hex code will not work since it is still invalid, but "default" will work.

ok good :)
