### ISSUE TITLE
Setting Borders on other program

### ISSUE THREAD

**Issue by leland37** [keifufu/cute-borders#17]
I tried adding the following to my config for the Windows Explorer Window to no effect.  

  - match: "Title"
    contains: "Windows Explorer"
    active_border_color: "#f8ff00"
    inactive_border_color: "#ffffff"

I need some guidance on how to configure it for other software.  I use Software Informer https://systeminformer.sourceforge.io/ to gather information on each application.  Unless you plan on implementing a proper configuration we the users need a lot of help in this area.

**Comment by keifufu** [comment]
Explorer seems to not actually ever contain "Windows Explorer" in the title, but instead whatever folder you are in.
This works:
```
- match: "Class"
  contains: "CabinetWClass"
  active_border_color: "#f8ff00"
  inactive_border_color: "#ffffff"
```
