### ISSUE TITLE
How to find the match for a program or window

### ISSUE THREAD

**Issue by leland37** [keifufu/cute-borders#18]
Are there specific tools you use to find the name of a window or program?  Something that would help us the users figure it out on our own rather than having to ask questions about each program.  It would be much appreciated to know and would cut down on your need to support each user/program every time someone has a question.  Thanks for answering my question about Explorer in my previous question.

**Comment by keifufu** [comment]
I use ShareX's window inspector tool.

Matching things can be a bit of a pain sometimes. The title isn't consistent, the class is some generic name, etc.
Someone did suggest adding executable names (eg. explorer.exe) to be matched, but there are a couple of issues with that so I haven't added that (yet?).

**Comment by leland37** [comment]
Matching to the Exe file would be ideal if possible.  Then there would be no question marks for us the users.  But for you as a programmer I am not sure how easy that would be to implement.
