### ISSUE TITLE
Feature Request: Add custom border to (Classic) Taskbar

### ISSUE THREAD

**Issue by Skyyblaze** [keifufu/cute-borders#2]
I just discovered Cute Borders today by accident and I love it, thanks for making this, it makes Windows look so much nicer :)

One feature request I have, would it be possible to have Cute Borders also add a custom colored border to the Windows 11 Taskbar and perhaps also to the "Classic" Taskbar when using programs such as StartAllBack?

**Comment by keifufu** [comment]
Unfortunately not possible, the borders in the current version are already built into Windows and cute borders is just telling Windows which color to set. The taskbar has no such border :/

**Comment by Skyyblaze** [comment]
Ah alright too bad, thanks for the explanation anyway :)
