### ISSUE TITLE
Border thickness

### ISSUE THREAD

**Issue by tapochek666** [keifufu/cute-borders#24]
Hello developer! Please add an option to change the border thickness.

**Comment by keifufu** [comment]
No.

**Comment by tapochek666** [comment]
Спасибо

**Comment by kleineluka** [comment]
This is already a feature in the Direct2D branch, why not direct the user to compile that branch or just merge the branches together in the future with an option..?

**Comment by keifufu** [comment]
> This is already a feature in the Direct2D branch, why not direct the user to compile that branch or just merge the branches together in the future with an option..?

See this comment: https://github.com/keifufu/cute-borders/pull/1#issuecomment-2443781161

**Comment by Undisputed00x** [comment]
@tapochek666 Maybe you could also use this for your needs [tacky-borders](https://github.com/lukeyou05/tacky-borders)

**Comment by tapochek666** [comment]
> @tapochek666 Maybe you could also use this for your needs [tacky-borders](https://github.com/lukeyou05/tacky-borders)
Unfortunately, tacky-borders doesn't work quite correctly with one application that I have installed. So I thought that the author of cute-borders would make an option to increase the thickness like in tacky-borders

**Comment by tapochek666** [comment]
> @tapochek666 Maybe you could also use this for your needs [tacky-borders](https://github.com/lukeyou05/tacky-borders)

Unfortunately, tacky-borders doesn't work quite correctly with one application that I have installed. So I thought that the author of cute-borders would make an option to increase the thickness like in tacky-borders
