### ISSUE TITLE
Increase thickness

### ISSUE THREAD

**Issue by winchestercanal** [keifufu/cute-borders#26]
I would like to control the thickness of the edges, to make them thicker or thinner to my liking!

**Comment by keifufu** [comment]
Not possible with how this is implemented due to windows itself not supporting borders thicker than 1px.

**Comment by winchestercanal** [comment]
> Not possible with how this is implemented due to windows itself not supporting borders thicker than 1px.

But what if I want to make the edges bigger?

**Comment by keifufu** [comment]
you cry
