### ISSUE TITLE
Request another update

### ISSUE THREAD

**Issue by jo-project** [keifufu/cute-borders#3]
I really love this. I just wanted to ask, did you think about making the border have a gradient color? Thank you!

**Comment by keifufu** [comment]
This is unfortunately impossible. The borders are drawn by windows itself, this program simply tells windows what to do.
Other than only being able to draw a static color, the width of the borders is also limited to 1px.

I have experimented with drawing these borders myself in #1, however it was very laggy and I believe drawing borders in such a way is not optimal in the slightest.

**Comment by jo-project** [comment]
Thank you so much @keifufu. Can't wait to see for your future product related to windows!
