### ISSUE TITLE
Remove/Hide 1px border

### ISSUE THREAD

**Issue by Undisputed00x** [keifufu/cute-borders#9]
Hi there, seeing that this project its still not dead, i'd like to know if it could be possible this feature to be implemented because i hate borders especially the Win11 Grey-ish one
<details><summary>Details</summary>
<p>

![Screenshot 2024-06-12 164558](https://github.com/keifufu/cute-borders/assets/80290008/71cda989-8d0a-4dcb-9cf2-fd16d1c01a98)

</p>
</details> 

 Tried to add alpha channel to color like `#00000000` to make it transparent but didn't work. Also tried to edit the **.msstyles** theme files but couldn't find any attribute that changes this. There is a [project](https://github.com/ALTaleX531/TranslucentFlyouts) which has made a `nobordercolor` option but only for context menu.

**Comment by keifufu** [comment]
So, you want to use this project to just hide the borders? Or is that grey border another one from the one modified by this project?

**Comment by Undisputed00x** [comment]
@keifufu Sorry for the confusion, well yes i just want to hide the borders 😅 and cant find any way closer that could do that besides your project.

**Comment by keifufu** [comment]
According to Microsoft docs this should be possible, I'll make a build later and send it to you here if you don't mind testing that?

**Comment by keifufu** [comment]
Please try this and instead of a hex color, simply put "transparent" as the color.

[cute-borders-transparent-test.zip](https://github.com/user-attachments/files/15807515/cute-borders-transparent-test.zip)

**Comment by Undisputed00x** [comment]
Thank you so much ❤️❤️ it works !
<details><summary>Picture</summary>
<p>

![Screenshot 2024-06-12 190720](https://github.com/keifufu/cute-borders/assets/80290008/4a553054-6196-4cdc-964d-4c2fdf4de3c1)

</p>
</details> 

**(A separate issue)** Also for the mod to work on also on some system apps like TaskManager, TaskScheduler etc. Admin privileges are needed to the mod 
<details><summary>Example picture</summary>
<p>

![Screenshot 2024-06-12 190915](https://github.com/keifufu/cute-borders/assets/80290008/298089d0-eeb7-439b-8311-f22dd66bed96)

</p>
</details>

**Comment by keifufu** [comment]
I can mention the administrator issue in the README if you want, for the auto_start in the config I dont think i can easily make it start as admin without prompting UAC. Thoughts?

I'll make a new release with the changes soon!

**Comment by Undisputed00x** [comment]
> I can mention the administrator issue in the README if you want, for the auto_start in the config I dont think i can easily make it start as admin without prompting UAC. Thoughts?
> 

Uhm.. create a task schedule for the mod to start with admin privileges that's a quick way to bypass UAC.

**Comment by keifufu** [comment]
Will probably do that later, create a new issue please
